### PR TITLE
Add cropping function.

### PR DESCRIPTION
**Pull request by rolandakiki**
This commit adds several functions needed to get a dem crop from a
set of geographic bounds. Rasterio was added for reading and affine was added for geographic transforms. pyproj was added for datum shifts. 
The bounds are first rounded (ceil and floor) to the nearest pixel to create a crop from the input geographic bounds. SRTM90 has a "px is point" convention by default, and (lon=0,lat=0) is the center of a pixel. This information, along with the resolution, is used to adjust the bounds to the center of pixels. The transform (px_is_area convention) along with the shape is also computed.
Then, the tiles included in the bounds are read(downloaded into the cache if not already present). Using the tile's bound, we find where to read and write into the final dem. 

Missing tiles are handled. Nodata values are replaced by NaNs. |Latitudes| > 60  are handled. 
 Bounds crossing the antimeridian are handled. However, when testing stitching two tiles along the antimeridian, for ex. 'srtm_72_16' & 'srtm_01_16' (bounds=(175, -20 + 1.1 * RES, 185 - 1.1 * RES, -15) ), a single column of nans is seen at the boundary. However, I believe that this is normal and the expected behaviour since the first column of 'srtm_01_16' in the original tile is nodata (nodata=-32768).

### CODE REVIEW

**Comment by rolandakiki** [comment]
Selection_266
Picture showing the nan column at the boundary (antimeridian example)

**Comment by kidanger** [comment]
I have the following stacktrace when using crop:
```python
import srtm4
srtm4.crop((131.50441280850092, 32.87230837727814, 131.63005124618715, 33.010445410841804), 'ellipsoidal')
```
```
Traceback (most recent call last):
  File "/home/anger/dev/srtm4/dbg.py", line 2, in <module>
    srtm4.crop((131.50441280850092, 32.87230837727814, 131.63005124618715, 33.010445410841804), 'ellipsoidal')
  File "/home/anger/dev/srtm4/srtm4.py", line 652, in crop
    raster, transform, crs = crop_at_continous_lon_limits(
  File "/home/anger/dev/srtm4/srtm4.py", line 583, in crop_at_continous_lon_limits
    raster = merge(datasets, transform=transform, shape=dem_shape)
  File "/home/anger/dev/srtm4/srtm4.py", line 489, in merge
    col, row, width, height = get_px_region(int_bounds, dataset.transform,
  File "/home/anger/dev/srtm4/srtm4.py", line 442, in get_px_region
    window.row_off - off), special_round(window.col_off - off)
  File "/home/anger/dev/srtm4/srtm4.py", line 414, in special_round
    assert rounded - val < eps, "Big rounding error induced !"
AssertionError: Big rounding error induced !
```
Do you know why the assert is triggered?

**Comment by rolandakiki** [comment]
> I have the following stacktrace when using crop:
> 
> ```python
> import srtm4
> srtm4.crop((131.50441280850092, 32.87230837727814, 131.63005124618715, 33.010445410841804), 'ellipsoidal')
> ```
> 
> ```
> Traceback (most recent call last):
>   File "srtm4/dbg.py", line 2, in <module>
>     srtm4.crop((131.50441280850092, 32.87230837727814, 131.63005124618715, 33.010445410841804), 'ellipsoidal')
>   File "srtm4/srtm4.py", line 652, in crop
>     raster, transform, crs = crop_at_continous_lon_limits(
>   File "srtm4/srtm4.py", line 583, in crop_at_continous_lon_limits
>     raster = merge(datasets, transform=transform, shape=dem_shape)
>   File "srtm4/srtm4.py", line 489, in merge
>     col, row, width, height = get_px_region(int_bounds, dataset.transform,
>   File "srtm4/srtm4.py", line 442, in get_px_region
>     window.row_off - off), special_round(window.col_off - off)
>   File "srtm4/srtm4.py", line 414, in special_round
>     assert rounded - val < eps, "Big rounding error induced !"
> AssertionError: Big rounding error induced !
> ```
> 
> Do you know why the assert is triggered?

I have not been able to reproduce the error. However, this is triggered because of the special_round function that I defined. It rounds values to the nearest integer while checking that the difference with the integer is less than eps=1e-2 (default value). It seems that this condition was not verified here. This may be due to a different rasterio version. What we are rounding here is the result of a rasterio.window.from_bounds() call (we want to have an integer window in pixel coordinates). I would like to be able to reproduce this, so can you send me please your rasterio version ?

**Review by mnhrdt — COMMENTED** [review]
The cropping function is nice, but this pull request represents a major change to the interface of this module.  The new dependencies are not trivial at all (especially rasterio).  Shouldn't all this go into a separate module?  It's nice to be able to download srtm4 tiles without depending on the rasterio behemoth.

**Comment by rolandakiki** [comment]
> The cropping function is nice, but this pull request represents a major change to the interface of this module. The new dependencies are not trivial at all (especially rasterio). Shouldn't all this go into a separate module? It's nice to be able to download srtm4 tiles without depending on the rasterio behemoth.

Yes indeed this is a good point. So would moving the new functionalities to a new file (let's say cropper.py) and handling the dependencies as extras (`pip install -e .["crop"]` for ex.) be a part of the solution (not entirely sure of all the details, but should be doable) ? Or should we just do another package srtm4-cropper at another repo ?

**Comment by mnhrdt** [comment]
I guess that just moving the crop function into a separate file within this repo would be enough.  That way you can install srtm4 without rasterio using "pip install --no-dependencies" and it will work.  A separate repo seems a bit of overkill.  (I never heard about handling dependencies as extras, but it seems nice also.)

**Comment by rolandakiki** [comment]
> I guess that just moving the crop function into a separate file within this repo would be enough. That way you can install srtm4 without rasterio using "pip install --no-dependencies" and it will work. A separate repo seems a bit of overkill. (I never heard about handling dependencies as extras, but it seems nice also.)

I have included a suggested organization. Ideally maybe we create a package instead of a set of modules. If you are able to push to this PR, is it possible to improve on this organization of the repo as I am not an expert in packaging ? Thank you !

**Comment by carlodef** [comment]
> I have included a suggested organization. Ideally maybe we create a package instead of a set of modules. If you are able to push to this PR, is it possible to improve on this organization of the repo as I am not an expert in packaging ? Thank you !

Hello @rolandakiki, I just pushed a commit that reorganises the code into a python package. Before this PR we had a single python _module_, `srtm4.py`. Now we have a single python _package_, `srtm4`, that contains a few modules. The previous interface is preserved thanks to a few imports in `srtm4/__init__.py`.

**Review by carlodef — APPROVED** [review]

**Pull request merged**
